### ISSUE TITLE
show command not work in fedora35

### ISSUE THREAD

**Issue by mylabzhen** [vrothberg/vgrep#173] opened 2022-03-31 03:08 UTC
`Enter a vgrep command: grep "struct page {" ./

Index File                                                 Line Content
    0 arch/microblaze/include/asm/io.h       14 #include <linux/mm.h>          /* Get struct page {...} */
    1 include/linux/mm_types.h               72 struct page {
    2 tools/testing/radix-tree/regression1.c 48 struct page {
    3 tools/testing/radix-tree/regression2.c 63 struct page {
    4 tools/virtio/linux/kernel.h            37 struct page {
Enter a vgrep command: show 1

WARN[0026] strconv.Atoi: parsing "\x1b[32m72\x1b[m": invalid syntax`

[root@fedora linux]# echo $EDITOR
vim

[root@fedora linux]# rpm -qa | grep vgrep
vgrep-2.5.1-3.fc35.x86_64

**Comment by vrothberg** [comment] 2022-03-31 06:14
Thanks for reaching out.

The issue has already been fixed with vgrep v2.6.0 (see https://github.com/vrothberg/vgrep/issues/169).  It's caused by a behavioral change in git - quite unfortunate.

The best workaround at the moment is to `dnf install ripgrep`.

I'll consider creating a backport to release v2.5.2 Fedora.

**Comment by vrothberg** [comment] 2022-03-31 06:50
I created v2.5.6 (https://github.com/vrothberg/vgrep/releases/tag/v2.5.6) so that distribution can pick up the fixes.  I'll try to bump it for F35.

**Closed by vrothberg** 2022-03-31 06:50 UTC
